### ISSUE TITLE
Pathfind won't detect OS on Alpine Linux

### ISSUE THREAD

**Issue by rsmmr** [bkloppenborg/pathfind#5]
https://github.com/bkloppenborg/pathfind/blob/d822a2f0a26ce8bd388cacc34c955fccc01c082d/src/pathfind.cpp#L88

`__gnu_linux__` isn't defined on Alpine, just `__linux__`.

**Comment by bkloppenborg** [comment]
Thanks for reporting the bug. Fixed in 669869a.

**Comment by rsmmr** [comment]
There are actually a couple of more places with the same issue, mind fixing those as well? Let me know if you'd prefer a PR.

**Comment by bkloppenborg** [comment]
Hi @rsmmr , I found three instances where __gnu_linux__ appears:

```
brian@epislon:~/workspace/pathfind$ grep -r "__gnu_linux__"
src/pathfind.hpp:#elif defined (BSD) || defined(__gnu_linux__) || defined(sun) || defined(__sun)	 // BSD, Linux, Solaris
src/pathfind.cpp:#if defined (BSD) || defined(__gnu_linux__) || defined(sun) || defined(__sun)
src/pathfind.cpp:#elif defined (__gnu_linux__)	|| defined (__linux__)// Linux
```
The first two weren't fixed in my last commit on this topic. I've added `__linux__` to the remaining locations:

```
brian@epislon:~/workspace/pathfind$ grep -r "__gnu_linux__"
src/pathfind.hpp:#elif defined (BSD) || defined(__gnu_linux__) || defined(__linux__) || defined(sun) || defined(__sun)	 // BSD, Linux, Solaris
src/pathfind.cpp:#if defined(BSD) || defined(__gnu_linux__) || defined(__linux__) || defined(sun) || defined(__sun)
src/pathfind.cpp:#elif defined (__gnu_linux__)	|| defined (__linux__)// Linux
```
in commit 27ff1ae. Please let me know if I've missed anything else. Thank you again!

**Comment by rsmmr** [comment]
Sorry, forgot to confirm this: it's working great now, thanks!

**Comment by bkloppenborg** [comment]
Excellent. I'm glad it worked out. Please let me know if you discover anything else that needs fixing!
